version: '3'
services:
  fileserver:
    image: 'node:16-alpine'
    container_name: 'fileserver' 
    working_dir: /src
    tty: true
    restart: always
    command: npm start
    environment:
      UPLOAD_MAX_CHUNK_SIZE: "5000"
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src:ro
      - ./storage:/storage

